// <auto-generated />
using System;
using BrasileiraoApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrasileiraoApi.Migrations
{
    [DbContext(typeof(BrasileiraoDbContext))]
    [Migration("20241110132849_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BrasileiraoApi.Entities.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdTitulo")
                        .HasColumnType("int");

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroCamisa")
                        .HasColumnType("longtext");

                    b.Property<string>("Posicao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("BrasileiraoApi.Entities.Titulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("JogadorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.ToTable("Titulos");
                });

            modelBuilder.Entity("BrasileiraoApi.Entities.Titulo", b =>
                {
                    b.HasOne("BrasileiraoApi.Entities.Jogador", "Jogador")
                        .WithMany("Titulos")
                        .HasForeignKey("JogadorId");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("BrasileiraoApi.Entities.Jogador", b =>
                {
                    b.Navigation("Titulos");
                });
#pragma warning restore 612, 618
        }
    }
}
